version: "3.5"
networks:
  vppnetwork:
    name: exchangenetwork

services:
  dev:
    container_name: node-template
    image: baidang201/exchange-node:release
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    networks:
      vppnetwork:
        aliases: 
          - exchangenetwork